artifact_uri: file:../mlruns_aws/1/bc18bb3ff1fa47d3a768b6ad3db7bb0a/artifacts
end_time: 1587855077863
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: bc18bb3ff1fa47d3a768b6ad3db7bb0a
run_uuid: bc18bb3ff1fa47d3a768b6ad3db7bb0a
source_name: ''
source_type: 4
source_version: ''
start_time: 1587854477158
status: 4
tags: []
user_id: ec2-user
