artifact_uri: file:../mlruns_aws/1/cd4e9df3218c4cd2a22e09719683b3d7/artifacts
end_time: 1588138698504
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: cd4e9df3218c4cd2a22e09719683b3d7
run_uuid: cd4e9df3218c4cd2a22e09719683b3d7
source_name: ''
source_type: 4
source_version: ''
start_time: 1588107101022
status: 3
tags: []
user_id: ec2-user
