artifact_uri: file:../mlruns_aws/1/b68979efc57e4068b09e60660581b2f1/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: b68979efc57e4068b09e60660581b2f1
run_uuid: b68979efc57e4068b09e60660581b2f1
source_name: ''
source_type: 4
source_version: ''
start_time: 1587230585105
status: 1
tags: []
user_id: ec2-user
