artifact_uri: file:../mlruns_aws/1/ef7f2b898ce24a559682a8f28d513dd5/artifacts
end_time: 1588050119983
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: ef7f2b898ce24a559682a8f28d513dd5
run_uuid: ef7f2b898ce24a559682a8f28d513dd5
source_name: ''
source_type: 4
source_version: ''
start_time: 1588018202270
status: 3
tags: []
user_id: ec2-user
