Reacher_one.app:
	wget https://s3-us-west-1.amazonaws.com/udacity-drlnd/P2/Reacher/one_agent/Reacher.app.zip
	unzip Reacher.app.zip
	mv Reacher.app Reacher_one.app
	rm Reacher.app.zip

Reacher_twenty.app:
	wget https://s3-us-west-1.amazonaws.com/udacity-drlnd/P2/Reacher/Reacher.app.zip
	unzip Reacher.app.zip
	mv Reacher.app Reacher_twenty.app
	rm Reacher.app.zip

Reacher_Linux_NoVis:
	wget https://s3-us-west-1.amazonaws.com/udacity-drlnd/P2/Reacher/one_agent/Reacher_Linux_NoVis.zip
	unzip Reacher_Linux_NoVis.zip
	# mv Reacher.app Reacher_one.app
	rm Reacher_Linux_NoVis.zip
